"""Copy logs from a consistent SQLite snapshot to an empty MySQL 8.0.40 or 8.0.46 table."""

import argparse
import hashlib
import json
import math
import os
import re
import sqlite3
import sys
from collections import Counter
from contextlib import closing
from datetime import datetime, timezone
from pathlib import Path

import pymysql

ROOT = Path(__file__).resolve().parents[1]
COLUMNS = (
    'id', 'ip_address', 'datetime', 'request_type', 'endpoint', 'http_version',
    'status_code', 'user_agent', 'Agent_Type', 'country', 'countryCode', 'region',
    'regionName', 'city', 'zip', 'lat', 'lon', 'timezone',
)
SELECT_ROWS = 'SELECT ' + ', '.join(f'`{name}`' for name in COLUMNS) + ' FROM logs ORDER BY id'
SQL_MODE = (
    'STRICT_ALL_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,'
    'NO_ENGINE_SUBSTITUTION,NO_AUTO_VALUE_ON_ZERO'
)


def mysql_settings(env_file: Path) -> dict:
    # Literal, unquoted KEY=VALUE entries, as generated by setup_credentials.py.
    values = {}
    for line in env_file.read_text(encoding='utf-8').splitlines():
        if line.strip() and not line.lstrip().startswith('#'):
            key, value = line.split('=', 1)
            values[key.strip()] = value.strip()
    for key in ('MYSQL_DATABASE', 'MYSQL_USER', 'MYSQL_PASSWORD'):
        if not values.get(key):
            raise ValueError(f'{env_file} is missing {key}')
    return dict(
        host=os.environ.get('MYSQL_HOST', '127.0.0.1'),
        port=int(os.environ.get('MYSQL_PORT', '3307')),
        user=values['MYSQL_USER'], password=values['MYSQL_PASSWORD'],
        database=values['MYSQL_DATABASE'], charset='utf8mb4',
        autocommit=False, connect_timeout=10, read_timeout=60, write_timeout=60,
    )


def sqlite_readonly(path: Path) -> sqlite3.Connection:
    conn = sqlite3.connect(path.resolve().as_uri() + '?mode=ro', uri=True)
    conn.execute('PRAGMA query_only=ON')
    return conn


def snapshot_database(source: Path, snapshot: Path) -> None:
    snapshot.parent.mkdir(parents=True, exist_ok=True)
    fd = os.open(snapshot, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    os.close(fd)
    with closing(sqlite_readonly(source)) as src, closing(sqlite3.connect(snapshot)) as dst:
        src.backup(dst)
    print(f'Snapshot: {snapshot}', flush=True)


def utc_datetime(value):
    if value is None:
        return None
    if isinstance(value, str):
        fraction = re.search(r'\d{2}:\d{2}:\d{2}\.(\d+)', value)
        if fraction and len(fraction[1]) > 6:
            raise ValueError('Timestamp has more than six fractional digits')
        value = datetime.fromisoformat(value)
    if not isinstance(value, datetime) or value.utcoffset() is None:
        raise ValueError('SQLite timestamps must include a timezone offset')
    value = value.astimezone(timezone.utc).replace(tzinfo=None)
    if value.year < 1000:
        raise ValueError('Timestamp is outside the MySQL DATETIME range')
    return value


def convert_row(row: tuple) -> tuple:
    result = list(row)
    result[2] = utc_datetime(result[2])
    for index, (name, value) in enumerate(zip(COLUMNS, result, strict=True)):
        if value is None:
            if name == 'id':
                raise ValueError('Missing id')
            continue
        if name == 'id':
            if type(value) is not int or not -(2**63) <= value < 2**63:
                raise ValueError('id must be a signed 64-bit integer')
        elif name == 'status_code':
            if type(value) is not int or not 0 <= value <= 65535:
                raise ValueError('status_code must fit SMALLINT UNSIGNED')
        elif name in ('lat', 'lon'):
            if not isinstance(value, (float, int)) or not math.isfinite(value):
                raise ValueError(f'{name} must be a finite number')
            result[index] = float(value)
        elif name != 'datetime':
            if not isinstance(value, str):
                raise ValueError(f'{name} must be text')
            limit = {'ip_address': 45, 'Agent_Type': 1}.get(name)
            if limit is not None and len(value) > limit:
                raise ValueError(f'{name} exceeds VARCHAR({limit})')
            if limit is None and len(value.encode('utf-8')) > 65535:
                raise ValueError(f'{name} exceeds the MySQL TEXT byte limit')
    return tuple(result)


def read_rows(snapshot: Path) -> list[tuple]:
    with closing(sqlite_readonly(snapshot)) as conn:
        if conn.execute('PRAGMA integrity_check').fetchall() != [('ok',)]:
            raise ValueError('SQLite snapshot failed integrity_check')
        columns = tuple(row[1] for row in conn.execute('PRAGMA table_info(logs)'))
        if columns != COLUMNS:
            raise ValueError(f'Unexpected SQLite columns: {columns}')
        rows = []
        for row in conn.execute(SELECT_ROWS):
            try:
                rows.append(convert_row(row))
            except (ValueError, TypeError, OverflowError) as exc:
                raise ValueError(f'Invalid source row id={row[0]}: {exc}') from exc
        return rows


def compare_rows(expected: list[tuple], actual: list[tuple]) -> None:
    if len(expected) != len(actual):
        raise ValueError(f'Row count mismatch: SQLite={len(expected)}, MySQL={len(actual)}')
    for left, right in zip(expected, actual, strict=True):
        if left != right:
            differences = [name for name, a, b in zip(COLUMNS, left, right, strict=True) if a != b]
            raise ValueError(f'Row mismatch at source id={left[0]}, columns={differences}')


def digest_rows(rows: list[tuple]) -> str:
    digest = hashlib.sha256()
    for row in rows:
        values = [v.isoformat(timespec='microseconds') if isinstance(v, datetime) else v for v in row]
        digest.update(json.dumps(values, ensure_ascii=False, separators=(',', ':'), allow_nan=False).encode('utf-8'))
        digest.update(b'\n')
    return digest.hexdigest()


def verify_target(conn, rows: list[tuple]) -> tuple[str, dict]:
    with conn.cursor() as cursor:
        cursor.execute(SELECT_ROWS)
        actual = list(cursor.fetchall())
        compare_rows(rows, actual)
        # Exercise SQL aggregation and collation on representative analysis queries.
        for column, index in [('countryCode', 10), ('status_code', 6), ('Agent_Type', 8), ('endpoint', 4)]:
            cursor.execute(f'SELECT `{column}`, COUNT(*) FROM logs GROUP BY `{column}`')
            if dict(cursor.fetchall()) != dict(Counter(row[index] for row in rows)):
                raise ValueError(f'Grouped totals mismatch for {column}')
        cursor.execute('SELECT DATE(datetime), COUNT(*) FROM logs GROUP BY DATE(datetime)')
        dates = Counter(row[2].date() if row[2] is not None else None for row in rows)
        if dict(cursor.fetchall()) != dict(dates):
            raise ValueError('Daily totals mismatch')
        cursor.execute(
            'SELECT AUTO_INCREMENT FROM information_schema.TABLES '
            'WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s', ('logs',),
        )
        next_id = cursor.fetchone()[0]
        if next_id is None or (rows and next_id <= rows[-1][0]):
            raise ValueError('AUTO_INCREMENT does not exceed the imported IDs')
    return digest_rows(actual), {'next_auto_increment': next_id, 'grouped_totals_match': True}


def run(args) -> dict:
    settings = mysql_settings(args.env_file)
    if not args.verify_only:
        with closing(pymysql.connect(**settings)) as conn, conn.cursor() as cursor:
            cursor.execute('SELECT COUNT(*) FROM logs')
            if cursor.fetchone()[0]:
                raise ValueError('Target logs table is not empty; use --verify-only with the original --snapshot')
        snapshot_database(args.source, args.snapshot)
    rows = read_rows(args.snapshot)
    source_digest = digest_rows(rows)
    with closing(pymysql.connect(**settings)) as conn:
        try:
            with conn.cursor() as cursor:
                cursor.execute('SELECT VERSION()')
                version = cursor.fetchone()[0]
                if version.split('-')[0] not in ('8.0.40', '8.0.46'):
                    raise ValueError(f'Expected MySQL 8.0.40 or 8.0.46, found {version}')
                cursor.execute("SET SESSION time_zone = '+00:00'")
                cursor.execute('SET SESSION sql_mode = %s', (SQL_MODE,))
                cursor.execute('SET SESSION information_schema_stats_expiry = 0')
                cursor.execute('SHOW COLUMNS FROM logs')
                if tuple(row[0] for row in cursor.fetchall()) != COLUMNS:
                    raise ValueError('Target columns do not match mysql/schema.sql')
                cursor.execute('SELECT ENGINE FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = %s', ('logs',))
                if cursor.fetchone()[0] != 'InnoDB':
                    raise ValueError('Target must use InnoDB for transactional imports')
                if not args.verify_only:
                    cursor.execute('SELECT id FROM logs FOR UPDATE')
                    if cursor.fetchone() is not None:
                        raise ValueError('Target logs table is not empty')
                    statement = 'INSERT INTO logs (' + ', '.join(f'`{name}`' for name in COLUMNS) + ') VALUES (' + ', '.join(['%s'] * len(COLUMNS)) + ')'
                    for start in range(0, len(rows), args.batch_size):
                        cursor.executemany(statement, rows[start:start + args.batch_size])
                        if cursor.warning_count:
                            raise ValueError('MySQL returned warnings during insertion; rolling back')
                        print(f'Inserted {min(start + args.batch_size, len(rows))}/{len(rows)} rows (pending commit)', flush=True)
            mysql_digest, checks = verify_target(conn, rows)
            if mysql_digest != source_digest:
                raise ValueError('Canonical row checksums do not match')
            conn.commit()
            with closing(pymysql.connect(**settings)) as confirmed:
                with confirmed.cursor() as cursor:
                    cursor.execute('SET SESSION information_schema_stats_expiry = 0')
                committed_digest, checks = verify_target(confirmed, rows)
                if committed_digest != source_digest:
                    raise ValueError('Committed row checksum mismatch')
        except Exception:
            conn.rollback()
            raise
    dates = [row[2] for row in rows if row[2] is not None]
    return {
        'verified_at_utc': datetime.now(timezone.utc).isoformat(),
        'mode': 'verify-only' if args.verify_only else 'import',
        'snapshot': str(args.snapshot.resolve()),
        'snapshot_sha256': hashlib.sha256(args.snapshot.read_bytes()).hexdigest(),
        'mysql_version': version, 'host': settings['host'], 'port': settings['port'],
        'database': settings['database'], 'table': 'logs',
        'row_count': len(rows), 'column_count': len(COLUMNS),
        'min_id': rows[0][0] if rows else None, 'max_id': rows[-1][0] if rows else None,
        'min_datetime_utc': min(dates).isoformat() if dates else None,
        'max_datetime_utc': max(dates).isoformat() if dates else None,
        'null_counts': {name: sum(row[i] is None for row in rows) for i, name in enumerate(COLUMNS)},
        'sqlite_rows_sha256': source_digest, 'mysql_rows_sha256': committed_digest,
        'all_columns_match': True, **checks,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=ROOT / 'data.philiplessner.com/logs.db')
    parser.add_argument('--env-file', type=Path, default=ROOT / '.mysql.env')
    parser.add_argument('--snapshot', type=Path, help='New snapshot path for import; existing snapshot for --verify-only')
    parser.add_argument('--verify-only', action='store_true')
    parser.add_argument('--batch-size', type=int, default=1000)
    parser.add_argument('--report', type=Path, default=ROOT / '.mysql-migration/report.json')
    args = parser.parse_args()
    if args.batch_size < 1:
        parser.error('--batch-size must be positive')
    if args.verify_only and args.snapshot is None:
        parser.error('--verify-only requires the original --snapshot')
    if args.snapshot is None:
        stamp = datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ')
        args.snapshot = ROOT / '.mysql-migration' / f'logs-{stamp}.db'
    try:
        if args.report.resolve() in (args.source.resolve(), args.snapshot.resolve(), args.env_file.resolve()):
            raise ValueError('Report path must differ from the source, snapshot, and credentials')
        report = run(args)
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(json.dumps(report, indent=2) + '\n', encoding='utf-8')
        print(f'Verified {report["row_count"]} rows across {report["column_count"]} columns; report: {args.report}')
        return 0
    except (ValueError, OSError, sqlite3.Error, pymysql.MySQLError) as exc:
        detail = f'MySQL error {exc.args[0]}' if isinstance(exc, pymysql.MySQLError) else str(exc)
        print(f'Migration failed: {detail}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    sys.exit(main())
